// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/cached_content.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Content that has been preprocessed and can be used in subsequent request
/// to GenerativeService.
///
/// Cached content can be only used with model it was created for.
public struct Google_Ai_Generativelanguage_V1beta_CachedContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Specifies when this resource will expire.
  public var expiration: Google_Ai_Generativelanguage_V1beta_CachedContent.OneOf_Expiration? = nil

  /// Timestamp in UTC of when this resource is considered expired.
  /// This is *always* provided on output, regardless of what was sent
  /// on input.
  public var expireTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .expireTime(let v)? = expiration {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {expiration = .expireTime(newValue)}
  }

  /// Input only. New TTL for this resource, input only.
  public var ttl: SwiftProtobuf.Google_Protobuf_Duration {
    get {
      if case .ttl(let v)? = expiration {return v}
      return SwiftProtobuf.Google_Protobuf_Duration()
    }
    set {expiration = .ttl(newValue)}
  }

  /// Optional. Identifier. The resource name referring to the cached content.
  /// Format: `cachedContents/{id}`
  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  /// Optional. Immutable. The user-generated meaningful display name of the
  /// cached content. Maximum 128 Unicode characters.
  public var displayName: String {
    get {return _displayName ?? String()}
    set {_displayName = newValue}
  }
  /// Returns true if `displayName` has been explicitly set.
  public var hasDisplayName: Bool {return self._displayName != nil}
  /// Clears the value of `displayName`. Subsequent reads from it will return its default value.
  public mutating func clearDisplayName() {self._displayName = nil}

  /// Required. Immutable. The name of the `Model` to use for cached content
  /// Format: `models/{model}`
  public var model: String {
    get {return _model ?? String()}
    set {_model = newValue}
  }
  /// Returns true if `model` has been explicitly set.
  public var hasModel: Bool {return self._model != nil}
  /// Clears the value of `model`. Subsequent reads from it will return its default value.
  public mutating func clearModel() {self._model = nil}

  /// Optional. Input only. Immutable. Developer set system instruction.
  /// Currently text only.
  public var systemInstruction: Google_Ai_Generativelanguage_V1beta_Content {
    get {return _systemInstruction ?? Google_Ai_Generativelanguage_V1beta_Content()}
    set {_systemInstruction = newValue}
  }
  /// Returns true if `systemInstruction` has been explicitly set.
  public var hasSystemInstruction: Bool {return self._systemInstruction != nil}
  /// Clears the value of `systemInstruction`. Subsequent reads from it will return its default value.
  public mutating func clearSystemInstruction() {self._systemInstruction = nil}

  /// Optional. Input only. Immutable. The content to cache.
  public var contents: [Google_Ai_Generativelanguage_V1beta_Content] = []

  /// Optional. Input only. Immutable. A list of `Tools` the model may use to
  /// generate the next response
  public var tools: [Google_Ai_Generativelanguage_V1beta_Tool] = []

  /// Optional. Input only. Immutable. Tool config. This config is shared for all
  /// tools.
  public var toolConfig: Google_Ai_Generativelanguage_V1beta_ToolConfig {
    get {return _toolConfig ?? Google_Ai_Generativelanguage_V1beta_ToolConfig()}
    set {_toolConfig = newValue}
  }
  /// Returns true if `toolConfig` has been explicitly set.
  public var hasToolConfig: Bool {return self._toolConfig != nil}
  /// Clears the value of `toolConfig`. Subsequent reads from it will return its default value.
  public mutating func clearToolConfig() {self._toolConfig = nil}

  /// Output only. Creation time of the cache entry.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {return self._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {self._createTime = nil}

  /// Output only. When the cache entry was last updated in UTC time.
  public var updateTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _updateTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_updateTime = newValue}
  }
  /// Returns true if `updateTime` has been explicitly set.
  public var hasUpdateTime: Bool {return self._updateTime != nil}
  /// Clears the value of `updateTime`. Subsequent reads from it will return its default value.
  public mutating func clearUpdateTime() {self._updateTime = nil}

  /// Output only. Metadata on the usage of the cached content.
  public var usageMetadata: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata {
    get {return _usageMetadata ?? Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata()}
    set {_usageMetadata = newValue}
  }
  /// Returns true if `usageMetadata` has been explicitly set.
  public var hasUsageMetadata: Bool {return self._usageMetadata != nil}
  /// Clears the value of `usageMetadata`. Subsequent reads from it will return its default value.
  public mutating func clearUsageMetadata() {self._usageMetadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Specifies when this resource will expire.
  public enum OneOf_Expiration: Equatable, Sendable {
    /// Timestamp in UTC of when this resource is considered expired.
    /// This is *always* provided on output, regardless of what was sent
    /// on input.
    case expireTime(SwiftProtobuf.Google_Protobuf_Timestamp)
    /// Input only. New TTL for this resource, input only.
    case ttl(SwiftProtobuf.Google_Protobuf_Duration)

  }

  /// Metadata on the usage of the cached content.
  public struct UsageMetadata: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Total number of tokens that the cached content consumes.
    public var totalTokenCount: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _displayName: String? = nil
  fileprivate var _model: String? = nil
  fileprivate var _systemInstruction: Google_Ai_Generativelanguage_V1beta_Content? = nil
  fileprivate var _toolConfig: Google_Ai_Generativelanguage_V1beta_ToolConfig? = nil
  fileprivate var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _updateTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _usageMetadata: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_CachedContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CachedContent"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    9: .standard(proto: "expire_time"),
    10: .same(proto: "ttl"),
    1: .same(proto: "name"),
    11: .standard(proto: "display_name"),
    2: .same(proto: "model"),
    3: .standard(proto: "system_instruction"),
    4: .same(proto: "contents"),
    5: .same(proto: "tools"),
    6: .standard(proto: "tool_config"),
    7: .standard(proto: "create_time"),
    8: .standard(proto: "update_time"),
    12: .standard(proto: "usage_metadata"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._model) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._systemInstruction) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.contents) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.tools) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._toolConfig) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._createTime) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._updateTime) }()
      case 9: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.expiration {
          hadOneofValue = true
          if case .expireTime(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.expiration = .expireTime(v)
        }
      }()
      case 10: try {
        var v: SwiftProtobuf.Google_Protobuf_Duration?
        var hadOneofValue = false
        if let current = self.expiration {
          hadOneofValue = true
          if case .ttl(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.expiration = .ttl(v)
        }
      }()
      case 11: try { try decoder.decodeSingularStringField(value: &self._displayName) }()
      case 12: try { try decoder.decodeSingularMessageField(value: &self._usageMetadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._model {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._systemInstruction {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.contents.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.contents, fieldNumber: 4)
    }
    if !self.tools.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tools, fieldNumber: 5)
    }
    try { if let v = self._toolConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._createTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._updateTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    switch self.expiration {
    case .expireTime?: try {
      guard case .expireTime(let v)? = self.expiration else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .ttl?: try {
      guard case .ttl(let v)? = self.expiration else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try { if let v = self._displayName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._usageMetadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_CachedContent, rhs: Google_Ai_Generativelanguage_V1beta_CachedContent) -> Bool {
    if lhs.expiration != rhs.expiration {return false}
    if lhs._name != rhs._name {return false}
    if lhs._displayName != rhs._displayName {return false}
    if lhs._model != rhs._model {return false}
    if lhs._systemInstruction != rhs._systemInstruction {return false}
    if lhs.contents != rhs.contents {return false}
    if lhs.tools != rhs.tools {return false}
    if lhs._toolConfig != rhs._toolConfig {return false}
    if lhs._createTime != rhs._createTime {return false}
    if lhs._updateTime != rhs._updateTime {return false}
    if lhs._usageMetadata != rhs._usageMetadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Google_Ai_Generativelanguage_V1beta_CachedContent.protoMessageName + ".UsageMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "total_token_count"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.totalTokenCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.totalTokenCount != 0 {
      try visitor.visitSingularInt32Field(value: self.totalTokenCount, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata, rhs: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata) -> Bool {
    if lhs.totalTokenCount != rhs.totalTokenCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
