// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/file.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A file uploaded to the API.
/// Next ID: 15
public struct Google_Ai_Generativelanguage_V1beta_File: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Metadata for the File.
  public var metadata: OneOf_Metadata? {
    get {return _storage._metadata}
    set {_uniqueStorage()._metadata = newValue}
  }

  /// Output only. Metadata for a video.
  public var videoMetadata: Google_Ai_Generativelanguage_V1beta_VideoMetadata {
    get {
      if case .videoMetadata(let v)? = _storage._metadata {return v}
      return Google_Ai_Generativelanguage_V1beta_VideoMetadata()
    }
    set {_uniqueStorage()._metadata = .videoMetadata(newValue)}
  }

  /// Immutable. Identifier. The `File` resource name. The ID (name excluding the
  /// "files/" prefix) can contain up to 40 characters that are lowercase
  /// alphanumeric or dashes (-). The ID cannot start or end with a dash. If the
  /// name is empty on create, a unique name will be generated. Example:
  /// `files/123-456`
  public var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// Optional. The human-readable display name for the `File`. The display name
  /// must be no more than 512 characters in length, including spaces. Example:
  /// "Welcome Image"
  public var displayName: String {
    get {return _storage._displayName}
    set {_uniqueStorage()._displayName = newValue}
  }

  /// Output only. MIME type of the file.
  public var mimeType: String {
    get {return _storage._mimeType}
    set {_uniqueStorage()._mimeType = newValue}
  }

  /// Output only. Size of the file in bytes.
  public var sizeBytes: Int64 {
    get {return _storage._sizeBytes}
    set {_uniqueStorage()._sizeBytes = newValue}
  }

  /// Output only. The timestamp of when the `File` was created.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {return _storage._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {_uniqueStorage()._createTime = nil}

  /// Output only. The timestamp of when the `File` was last updated.
  public var updateTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._updateTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._updateTime = newValue}
  }
  /// Returns true if `updateTime` has been explicitly set.
  public var hasUpdateTime: Bool {return _storage._updateTime != nil}
  /// Clears the value of `updateTime`. Subsequent reads from it will return its default value.
  public mutating func clearUpdateTime() {_uniqueStorage()._updateTime = nil}

  /// Output only. The timestamp of when the `File` will be deleted. Only set if
  /// the `File` is scheduled to expire.
  public var expirationTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._expirationTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._expirationTime = newValue}
  }
  /// Returns true if `expirationTime` has been explicitly set.
  public var hasExpirationTime: Bool {return _storage._expirationTime != nil}
  /// Clears the value of `expirationTime`. Subsequent reads from it will return its default value.
  public mutating func clearExpirationTime() {_uniqueStorage()._expirationTime = nil}

  /// Output only. SHA-256 hash of the uploaded bytes.
  public var sha256Hash: Data {
    get {return _storage._sha256Hash}
    set {_uniqueStorage()._sha256Hash = newValue}
  }

  /// Output only. The uri of the `File`.
  public var uri: String {
    get {return _storage._uri}
    set {_uniqueStorage()._uri = newValue}
  }

  /// Output only. The download uri of the `File`.
  public var downloadUri: String {
    get {return _storage._downloadUri}
    set {_uniqueStorage()._downloadUri = newValue}
  }

  /// Output only. Processing state of the File.
  public var state: Google_Ai_Generativelanguage_V1beta_File.State {
    get {return _storage._state}
    set {_uniqueStorage()._state = newValue}
  }

  /// Source of the File.
  public var source: Google_Ai_Generativelanguage_V1beta_File.Source {
    get {return _storage._source}
    set {_uniqueStorage()._source = newValue}
  }

  /// Output only. Error status if File processing failed.
  public var error: Google_Rpc_Status {
    get {return _storage._error ?? Google_Rpc_Status()}
    set {_uniqueStorage()._error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return _storage._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {_uniqueStorage()._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Metadata for the File.
  public enum OneOf_Metadata: Equatable, Sendable {
    /// Output only. Metadata for a video.
    case videoMetadata(Google_Ai_Generativelanguage_V1beta_VideoMetadata)

  }

  /// States for the lifecycle of a File.
  public enum State: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// The default value. This value is used if the state is omitted.
    case unspecified // = 0

    /// File is being processed and cannot be used for inference yet.
    case processing // = 1

    /// File is processed and available for inference.
    case active // = 2

    /// File failed processing.
    case failed // = 10
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .processing
      case 2: self = .active
      case 10: self = .failed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .processing: return 1
      case .active: return 2
      case .failed: return 10
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Google_Ai_Generativelanguage_V1beta_File.State] = [
      .unspecified,
      .processing,
      .active,
      .failed,
    ]

  }

  public enum Source: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// Used if source is not specified.
    case unspecified // = 0

    /// Indicates the file is uploaded by the user.
    case uploaded // = 1

    /// Indicates the file is generated by Google.
    case generated // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .uploaded
      case 2: self = .generated
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .uploaded: return 1
      case .generated: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Google_Ai_Generativelanguage_V1beta_File.Source] = [
      .unspecified,
      .uploaded,
      .generated,
    ]

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Metadata for a video `File`.
public struct Google_Ai_Generativelanguage_V1beta_VideoMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Duration of the video.
  public var videoDuration: SwiftProtobuf.Google_Protobuf_Duration {
    get {return _videoDuration ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_videoDuration = newValue}
  }
  /// Returns true if `videoDuration` has been explicitly set.
  public var hasVideoDuration: Bool {return self._videoDuration != nil}
  /// Clears the value of `videoDuration`. Subsequent reads from it will return its default value.
  public mutating func clearVideoDuration() {self._videoDuration = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _videoDuration: SwiftProtobuf.Google_Protobuf_Duration? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_File: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".File"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    12: .standard(proto: "video_metadata"),
    1: .same(proto: "name"),
    2: .standard(proto: "display_name"),
    3: .standard(proto: "mime_type"),
    4: .standard(proto: "size_bytes"),
    5: .standard(proto: "create_time"),
    6: .standard(proto: "update_time"),
    7: .standard(proto: "expiration_time"),
    8: .standard(proto: "sha256_hash"),
    9: .same(proto: "uri"),
    14: .standard(proto: "download_uri"),
    10: .same(proto: "state"),
    13: .same(proto: "source"),
    11: .same(proto: "error"),
  ]

  fileprivate class _StorageClass {
    var _metadata: Google_Ai_Generativelanguage_V1beta_File.OneOf_Metadata?
    var _name: String = String()
    var _displayName: String = String()
    var _mimeType: String = String()
    var _sizeBytes: Int64 = 0
    var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _updateTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _expirationTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _sha256Hash: Data = Data()
    var _uri: String = String()
    var _downloadUri: String = String()
    var _state: Google_Ai_Generativelanguage_V1beta_File.State = .unspecified
    var _source: Google_Ai_Generativelanguage_V1beta_File.Source = .unspecified
    var _error: Google_Rpc_Status? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _metadata = source._metadata
      _name = source._name
      _displayName = source._displayName
      _mimeType = source._mimeType
      _sizeBytes = source._sizeBytes
      _createTime = source._createTime
      _updateTime = source._updateTime
      _expirationTime = source._expirationTime
      _sha256Hash = source._sha256Hash
      _uri = source._uri
      _downloadUri = source._downloadUri
      _state = source._state
      _source = source._source
      _error = source._error
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._displayName) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._mimeType) }()
        case 4: try { try decoder.decodeSingularInt64Field(value: &_storage._sizeBytes) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._createTime) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._updateTime) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._expirationTime) }()
        case 8: try { try decoder.decodeSingularBytesField(value: &_storage._sha256Hash) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._uri) }()
        case 10: try { try decoder.decodeSingularEnumField(value: &_storage._state) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._error) }()
        case 12: try {
          var v: Google_Ai_Generativelanguage_V1beta_VideoMetadata?
          var hadOneofValue = false
          if let current = _storage._metadata {
            hadOneofValue = true
            if case .videoMetadata(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._metadata = .videoMetadata(v)
          }
        }()
        case 13: try { try decoder.decodeSingularEnumField(value: &_storage._source) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._downloadUri) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      if !_storage._displayName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._displayName, fieldNumber: 2)
      }
      if !_storage._mimeType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._mimeType, fieldNumber: 3)
      }
      if _storage._sizeBytes != 0 {
        try visitor.visitSingularInt64Field(value: _storage._sizeBytes, fieldNumber: 4)
      }
      try { if let v = _storage._createTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._updateTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._expirationTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if !_storage._sha256Hash.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._sha256Hash, fieldNumber: 8)
      }
      if !_storage._uri.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uri, fieldNumber: 9)
      }
      if _storage._state != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._state, fieldNumber: 10)
      }
      try { if let v = _storage._error {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if case .videoMetadata(let v)? = _storage._metadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      if _storage._source != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._source, fieldNumber: 13)
      }
      if !_storage._downloadUri.isEmpty {
        try visitor.visitSingularStringField(value: _storage._downloadUri, fieldNumber: 14)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_File, rhs: Google_Ai_Generativelanguage_V1beta_File) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._metadata != rhs_storage._metadata {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._displayName != rhs_storage._displayName {return false}
        if _storage._mimeType != rhs_storage._mimeType {return false}
        if _storage._sizeBytes != rhs_storage._sizeBytes {return false}
        if _storage._createTime != rhs_storage._createTime {return false}
        if _storage._updateTime != rhs_storage._updateTime {return false}
        if _storage._expirationTime != rhs_storage._expirationTime {return false}
        if _storage._sha256Hash != rhs_storage._sha256Hash {return false}
        if _storage._uri != rhs_storage._uri {return false}
        if _storage._downloadUri != rhs_storage._downloadUri {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._source != rhs_storage._source {return false}
        if _storage._error != rhs_storage._error {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_File.State: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "STATE_UNSPECIFIED"),
    1: .same(proto: "PROCESSING"),
    2: .same(proto: "ACTIVE"),
    10: .same(proto: "FAILED"),
  ]
}

extension Google_Ai_Generativelanguage_V1beta_File.Source: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SOURCE_UNSPECIFIED"),
    1: .same(proto: "UPLOADED"),
    2: .same(proto: "GENERATED"),
  ]
}

extension Google_Ai_Generativelanguage_V1beta_VideoMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoMetadata"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "video_duration"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._videoDuration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._videoDuration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_VideoMetadata, rhs: Google_Ai_Generativelanguage_V1beta_VideoMetadata) -> Bool {
    if lhs._videoDuration != rhs._videoDuration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
