// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/model.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Information about a Generative Language Model.
public struct Google_Ai_Generativelanguage_V1beta_Model: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The resource name of the `Model`. Refer to [Model
  /// variants](https://ai.google.dev/gemini-api/docs/models/gemini#model-variations)
  /// for all allowed values.
  ///
  /// Format: `models/{model}` with a `{model}` naming convention of:
  ///
  /// * "{base_model_id}-{version}"
  ///
  /// Examples:
  ///
  /// * `models/gemini-1.5-flash-001`
  public var name: String = String()

  /// Required. The name of the base model, pass this to the generation request.
  ///
  /// Examples:
  ///
  /// * `gemini-1.5-flash`
  public var baseModelID: String = String()

  /// Required. The version number of the model.
  ///
  /// This represents the major version (`1.0` or `1.5`)
  public var version: String = String()

  /// The human-readable name of the model. E.g. "Gemini 1.5 Flash".
  ///
  /// The name can be up to 128 characters long and can consist of any UTF-8
  /// characters.
  public var displayName: String = String()

  /// A short description of the model.
  public var description_p: String = String()

  /// Maximum number of input tokens allowed for this model.
  public var inputTokenLimit: Int32 = 0

  /// Maximum number of output tokens available for this model.
  public var outputTokenLimit: Int32 = 0

  /// The model's supported generation methods.
  ///
  /// The corresponding API method names are defined as Pascal case
  /// strings, such as `generateMessage` and `generateContent`.
  public var supportedGenerationMethods: [String] = []

  /// Controls the randomness of the output.
  ///
  /// Values can range over `[0.0,max_temperature]`, inclusive. A higher value
  /// will produce responses that are more varied, while a value closer to `0.0`
  /// will typically result in less surprising responses from the model.
  /// This value specifies default to be used by the backend while making the
  /// call to the model.
  public var temperature: Float {
    get {return _temperature ?? 0}
    set {_temperature = newValue}
  }
  /// Returns true if `temperature` has been explicitly set.
  public var hasTemperature: Bool {return self._temperature != nil}
  /// Clears the value of `temperature`. Subsequent reads from it will return its default value.
  public mutating func clearTemperature() {self._temperature = nil}

  /// The maximum temperature this model can use.
  public var maxTemperature: Float {
    get {return _maxTemperature ?? 0}
    set {_maxTemperature = newValue}
  }
  /// Returns true if `maxTemperature` has been explicitly set.
  public var hasMaxTemperature: Bool {return self._maxTemperature != nil}
  /// Clears the value of `maxTemperature`. Subsequent reads from it will return its default value.
  public mutating func clearMaxTemperature() {self._maxTemperature = nil}

  /// For [Nucleus
  /// sampling](https://ai.google.dev/gemini-api/docs/prompting-strategies#top-p).
  ///
  /// Nucleus sampling considers the smallest set of tokens whose probability
  /// sum is at least `top_p`.
  /// This value specifies default to be used by the backend while making the
  /// call to the model.
  public var topP: Float {
    get {return _topP ?? 0}
    set {_topP = newValue}
  }
  /// Returns true if `topP` has been explicitly set.
  public var hasTopP: Bool {return self._topP != nil}
  /// Clears the value of `topP`. Subsequent reads from it will return its default value.
  public mutating func clearTopP() {self._topP = nil}

  /// For Top-k sampling.
  ///
  /// Top-k sampling considers the set of `top_k` most probable tokens.
  /// This value specifies default to be used by the backend while making the
  /// call to the model.
  /// If empty, indicates the model doesn't use top-k sampling, and `top_k` isn't
  /// allowed as a generation parameter.
  public var topK: Int32 {
    get {return _topK ?? 0}
    set {_topK = newValue}
  }
  /// Returns true if `topK` has been explicitly set.
  public var hasTopK: Bool {return self._topK != nil}
  /// Clears the value of `topK`. Subsequent reads from it will return its default value.
  public mutating func clearTopK() {self._topK = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _temperature: Float? = nil
  fileprivate var _maxTemperature: Float? = nil
  fileprivate var _topP: Float? = nil
  fileprivate var _topK: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_Model: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Model"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "base_model_id"),
    3: .same(proto: "version"),
    4: .standard(proto: "display_name"),
    5: .same(proto: "description"),
    6: .standard(proto: "input_token_limit"),
    7: .standard(proto: "output_token_limit"),
    8: .standard(proto: "supported_generation_methods"),
    9: .same(proto: "temperature"),
    13: .standard(proto: "max_temperature"),
    10: .standard(proto: "top_p"),
    11: .standard(proto: "top_k"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.baseModelID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.inputTokenLimit) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.outputTokenLimit) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.supportedGenerationMethods) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self._temperature) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self._topP) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self._topK) }()
      case 13: try { try decoder.decodeSingularFloatField(value: &self._maxTemperature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.baseModelID.isEmpty {
      try visitor.visitSingularStringField(value: self.baseModelID, fieldNumber: 2)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 3)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 4)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 5)
    }
    if self.inputTokenLimit != 0 {
      try visitor.visitSingularInt32Field(value: self.inputTokenLimit, fieldNumber: 6)
    }
    if self.outputTokenLimit != 0 {
      try visitor.visitSingularInt32Field(value: self.outputTokenLimit, fieldNumber: 7)
    }
    if !self.supportedGenerationMethods.isEmpty {
      try visitor.visitRepeatedStringField(value: self.supportedGenerationMethods, fieldNumber: 8)
    }
    try { if let v = self._temperature {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._topP {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._topK {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._maxTemperature {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_Model, rhs: Google_Ai_Generativelanguage_V1beta_Model) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.baseModelID != rhs.baseModelID {return false}
    if lhs.version != rhs.version {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.inputTokenLimit != rhs.inputTokenLimit {return false}
    if lhs.outputTokenLimit != rhs.outputTokenLimit {return false}
    if lhs.supportedGenerationMethods != rhs.supportedGenerationMethods {return false}
    if lhs._temperature != rhs._temperature {return false}
    if lhs._maxTemperature != rhs._maxTemperature {return false}
    if lhs._topP != rhs._topP {return false}
    if lhs._topK != rhs._topK {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
