// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/permission.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Permission resource grants user, group or the rest of the world access to the
/// PaLM API resource (e.g. a tuned model, corpus).
///
/// A role is a collection of permitted operations that allows users to perform
/// specific actions on PaLM API resources. To make them available to users,
/// groups, or service accounts, you assign roles. When you assign a role, you
/// grant permissions that the role contains.
///
/// There are three concentric roles. Each role is a superset of the previous
/// role's permitted operations:
///
/// - reader can use the resource (e.g. tuned model, corpus) for inference
/// - writer has reader's permissions and additionally can edit and share
/// - owner has writer's permissions and additionally can delete
public struct Google_Ai_Generativelanguage_V1beta_Permission: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Output only. Identifier. The permission name. A unique name will be
  /// generated on create. Examples:
  ///     tunedModels/{tuned_model}/permissions/{permission}
  ///     corpora/{corpus}/permissions/{permission}
  /// Output only.
  public var name: String = String()

  /// Optional. Immutable. The type of the grantee.
  public var granteeType: Google_Ai_Generativelanguage_V1beta_Permission.GranteeType {
    get {return _granteeType ?? .unspecified}
    set {_granteeType = newValue}
  }
  /// Returns true if `granteeType` has been explicitly set.
  public var hasGranteeType: Bool {return self._granteeType != nil}
  /// Clears the value of `granteeType`. Subsequent reads from it will return its default value.
  public mutating func clearGranteeType() {self._granteeType = nil}

  /// Optional. Immutable. The email address of the user of group which this
  /// permission refers. Field is not set when permission's grantee type is
  /// EVERYONE.
  public var emailAddress: String {
    get {return _emailAddress ?? String()}
    set {_emailAddress = newValue}
  }
  /// Returns true if `emailAddress` has been explicitly set.
  public var hasEmailAddress: Bool {return self._emailAddress != nil}
  /// Clears the value of `emailAddress`. Subsequent reads from it will return its default value.
  public mutating func clearEmailAddress() {self._emailAddress = nil}

  /// Required. The role granted by this permission.
  public var role: Google_Ai_Generativelanguage_V1beta_Permission.Role {
    get {return _role ?? .unspecified}
    set {_role = newValue}
  }
  /// Returns true if `role` has been explicitly set.
  public var hasRole: Bool {return self._role != nil}
  /// Clears the value of `role`. Subsequent reads from it will return its default value.
  public mutating func clearRole() {self._role = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Defines types of the grantee of this permission.
  public enum GranteeType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// The default value. This value is unused.
    case unspecified // = 0

    /// Represents a user. When set, you must provide email_address for the user.
    case user // = 1

    /// Represents a group. When set, you must provide email_address for the
    /// group.
    case group // = 2

    /// Represents access to everyone. No extra information is required.
    case everyone // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .user
      case 2: self = .group
      case 3: self = .everyone
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .user: return 1
      case .group: return 2
      case .everyone: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Google_Ai_Generativelanguage_V1beta_Permission.GranteeType] = [
      .unspecified,
      .user,
      .group,
      .everyone,
    ]

  }

  /// Defines the role granted by this permission.
  public enum Role: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int

    /// The default value. This value is unused.
    case unspecified // = 0

    /// Owner can use, update, share and delete the resource.
    case owner // = 1

    /// Writer can use, update and share the resource.
    case writer // = 2

    /// Reader can use the resource.
    case reader // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .owner
      case 2: self = .writer
      case 3: self = .reader
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .owner: return 1
      case .writer: return 2
      case .reader: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Google_Ai_Generativelanguage_V1beta_Permission.Role] = [
      .unspecified,
      .owner,
      .writer,
      .reader,
    ]

  }

  public init() {}

  fileprivate var _granteeType: Google_Ai_Generativelanguage_V1beta_Permission.GranteeType? = nil
  fileprivate var _emailAddress: String? = nil
  fileprivate var _role: Google_Ai_Generativelanguage_V1beta_Permission.Role? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_Permission: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Permission"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "grantee_type"),
    3: .standard(proto: "email_address"),
    4: .same(proto: "role"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._granteeType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._emailAddress) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._role) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._granteeType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._emailAddress {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._role {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_Permission, rhs: Google_Ai_Generativelanguage_V1beta_Permission) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._granteeType != rhs._granteeType {return false}
    if lhs._emailAddress != rhs._emailAddress {return false}
    if lhs._role != rhs._role {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_Permission.GranteeType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "GRANTEE_TYPE_UNSPECIFIED"),
    1: .same(proto: "USER"),
    2: .same(proto: "GROUP"),
    3: .same(proto: "EVERYONE"),
  ]
}

extension Google_Ai_Generativelanguage_V1beta_Permission.Role: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ROLE_UNSPECIFIED"),
    1: .same(proto: "OWNER"),
    2: .same(proto: "WRITER"),
    3: .same(proto: "READER"),
  ]
}
