// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/cache_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - google.ai.generativelanguage.v1beta.CacheService

/// Namespace containing generated types for the "google.ai.generativelanguage.v1beta.CacheService" service.
public enum Google_Ai_Generativelanguage_V1beta_CacheService {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.CacheService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "ListCachedContents" metadata.
        public enum ListCachedContents {
            /// Request type for "ListCachedContents".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest
            /// Response type for "ListCachedContents".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse
            /// Descriptor for "ListCachedContents".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService"),
                method: "ListCachedContents"
            )
        }
        /// Namespace for "CreateCachedContent" metadata.
        public enum CreateCachedContent {
            /// Request type for "CreateCachedContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest
            /// Response type for "CreateCachedContent".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_CachedContent
            /// Descriptor for "CreateCachedContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService"),
                method: "CreateCachedContent"
            )
        }
        /// Namespace for "GetCachedContent" metadata.
        public enum GetCachedContent {
            /// Request type for "GetCachedContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest
            /// Response type for "GetCachedContent".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_CachedContent
            /// Descriptor for "GetCachedContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService"),
                method: "GetCachedContent"
            )
        }
        /// Namespace for "UpdateCachedContent" metadata.
        public enum UpdateCachedContent {
            /// Request type for "UpdateCachedContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest
            /// Response type for "UpdateCachedContent".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_CachedContent
            /// Descriptor for "UpdateCachedContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService"),
                method: "UpdateCachedContent"
            )
        }
        /// Namespace for "DeleteCachedContent" metadata.
        public enum DeleteCachedContent {
            /// Request type for "DeleteCachedContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest
            /// Response type for "DeleteCachedContent".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "DeleteCachedContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService"),
                method: "DeleteCachedContent"
            )
        }
        /// Descriptors for all methods in the "google.ai.generativelanguage.v1beta.CacheService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            ListCachedContents.descriptor,
            CreateCachedContent.descriptor,
            GetCachedContent.descriptor,
            UpdateCachedContent.descriptor,
            DeleteCachedContent.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.CacheService" service.
    public static let google_ai_generativelanguage_v1Beta_CacheService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.CacheService")
}

// MARK: google.ai.generativelanguage.v1beta.CacheService (client)

extension Google_Ai_Generativelanguage_V1beta_CacheService {
    /// Generated client protocol for the "google.ai.generativelanguage.v1beta.CacheService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > API for managing cache of content (CachedContent resources) that can be used
    /// > in GenerativeService requests. This way generate content requests can benefit
    /// > from preprocessing work being done earlier, possibly lowering their
    /// > computational cost. It is intended to be used with large contexts.
    public protocol ClientProtocol: Sendable {
        /// Call the "ListCachedContents" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists CachedContents.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listCachedContents<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates CachedContent resource.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CachedContent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Reads CachedContent resource.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CachedContent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Updates CachedContent resource (only expiration is updatable).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CachedContent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Deletes CachedContent resource.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "google.ai.generativelanguage.v1beta.CacheService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > API for managing cache of content (CachedContent resources) that can be used
    /// > in GenerativeService requests. This way generate content requests can benefit
    /// > from preprocessing work being done earlier, possibly lowering their
    /// > computational cost. It is intended to be used with large contexts.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ListCachedContents" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists CachedContents.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listCachedContents<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_CacheService.Method.ListCachedContents.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates CachedContent resource.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CachedContent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_CacheService.Method.CreateCachedContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Reads CachedContent resource.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CachedContent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_CacheService.Method.GetCachedContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Updates CachedContent resource (only expiration is updatable).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CachedContent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_CacheService.Method.UpdateCachedContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteCachedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Deletes CachedContent resource.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteCachedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_CacheService.Method.DeleteCachedContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_CacheService.ClientProtocol {
    /// Call the "ListCachedContents" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists CachedContents.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listCachedContents<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listCachedContents(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates CachedContent resource.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createCachedContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createCachedContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Reads CachedContent resource.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getCachedContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getCachedContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Updates CachedContent resource (only expiration is updatable).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateCachedContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateCachedContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_CachedContent>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Deletes CachedContent resource.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteCachedContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteCachedContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_CacheService.ClientProtocol {
    /// Call the "ListCachedContents" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists CachedContents.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listCachedContents<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListCachedContentsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListCachedContentsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listCachedContents(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates CachedContent resource.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createCachedContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateCachedContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createCachedContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Reads CachedContent resource.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getCachedContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetCachedContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getCachedContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Updates CachedContent resource (only expiration is updatable).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateCachedContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CachedContent>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_UpdateCachedContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateCachedContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteCachedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Deletes CachedContent resource.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteCachedContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteCachedContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteCachedContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}