// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/file_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - google.ai.generativelanguage.v1beta.FileService

/// Namespace containing generated types for the "google.ai.generativelanguage.v1beta.FileService" service.
public enum Google_Ai_Generativelanguage_V1beta_FileService {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.FileService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.FileService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "CreateFile" metadata.
        public enum CreateFile {
            /// Request type for "CreateFile".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_CreateFileRequest
            /// Response type for "CreateFile".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_CreateFileResponse
            /// Descriptor for "CreateFile".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.FileService"),
                method: "CreateFile"
            )
        }
        /// Namespace for "ListFiles" metadata.
        public enum ListFiles {
            /// Request type for "ListFiles".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_ListFilesRequest
            /// Response type for "ListFiles".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_ListFilesResponse
            /// Descriptor for "ListFiles".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.FileService"),
                method: "ListFiles"
            )
        }
        /// Namespace for "GetFile" metadata.
        public enum GetFile {
            /// Request type for "GetFile".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_GetFileRequest
            /// Response type for "GetFile".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_File
            /// Descriptor for "GetFile".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.FileService"),
                method: "GetFile"
            )
        }
        /// Namespace for "DeleteFile" metadata.
        public enum DeleteFile {
            /// Request type for "DeleteFile".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_DeleteFileRequest
            /// Response type for "DeleteFile".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "DeleteFile".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.FileService"),
                method: "DeleteFile"
            )
        }
        /// Descriptors for all methods in the "google.ai.generativelanguage.v1beta.FileService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            CreateFile.descriptor,
            ListFiles.descriptor,
            GetFile.descriptor,
            DeleteFile.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.FileService" service.
    public static let google_ai_generativelanguage_v1Beta_FileService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.FileService")
}

// MARK: google.ai.generativelanguage.v1beta.FileService (client)

extension Google_Ai_Generativelanguage_V1beta_FileService {
    /// Generated client protocol for the "google.ai.generativelanguage.v1beta.FileService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API for uploading and managing files.
    public protocol ClientProtocol: Sendable {
        /// Call the "CreateFile" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates a `File`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CreateFileRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CreateFileRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CreateFileResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createFile<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListFiles" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists the metadata for `File`s owned by the requesting project.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_ListFilesRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_ListFilesRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_ListFilesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listFiles<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetFile" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets the metadata for the given `File`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GetFileRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GetFileRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_File` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getFile<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetFileRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GetFileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_File>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_File>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteFile" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Deletes the `File`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_DeleteFileRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_DeleteFileRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteFile<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "google.ai.generativelanguage.v1beta.FileService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API for uploading and managing files.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "CreateFile" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates a `File`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CreateFileRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CreateFileRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CreateFileResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createFile<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_FileService.Method.CreateFile.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListFiles" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists the metadata for `File`s owned by the requesting project.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_ListFilesRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_ListFilesRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_ListFilesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listFiles<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_FileService.Method.ListFiles.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetFile" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets the metadata for the given `File`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GetFileRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GetFileRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_File` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getFile<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetFileRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GetFileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_File>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_File>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_FileService.Method.GetFile.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteFile" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Deletes the `File`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_DeleteFileRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_DeleteFileRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteFile<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_FileService.Method.DeleteFile.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_FileService.ClientProtocol {
    /// Call the "CreateFile" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates a `File`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CreateFileRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createFile<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createFile(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListFiles" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists the metadata for `File`s owned by the requesting project.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_ListFilesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listFiles<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listFiles(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetFile" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets the metadata for the given `File`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GetFileRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getFile<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetFileRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_File>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getFile(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_GetFileRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_File>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteFile" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Deletes the `File`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_DeleteFileRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteFile<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteFile(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_FileService.ClientProtocol {
    /// Call the "CreateFile" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates a `File`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createFile<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_CreateFileRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CreateFileResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CreateFileRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createFile(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListFiles" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists the metadata for `File`s owned by the requesting project.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listFiles<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_ListFilesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_ListFilesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_ListFilesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listFiles(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetFile" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets the metadata for the given `File`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getFile<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_GetFileRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_File>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GetFileRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getFile(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteFile" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Deletes the `File`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteFile<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_DeleteFileRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_DeleteFileRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteFile(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}