// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/generative_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - google.ai.generativelanguage.v1beta.GenerativeService

/// Namespace containing generated types for the "google.ai.generativelanguage.v1beta.GenerativeService" service.
public enum Google_Ai_Generativelanguage_V1beta_GenerativeService {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.GenerativeService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GenerateContent" metadata.
        public enum GenerateContent {
            /// Request type for "GenerateContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_GenerateContentRequest
            /// Response type for "GenerateContent".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_GenerateContentResponse
            /// Descriptor for "GenerateContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService"),
                method: "GenerateContent"
            )
        }
        /// Namespace for "GenerateAnswer" metadata.
        public enum GenerateAnswer {
            /// Request type for "GenerateAnswer".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest
            /// Response type for "GenerateAnswer".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse
            /// Descriptor for "GenerateAnswer".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService"),
                method: "GenerateAnswer"
            )
        }
        /// Namespace for "StreamGenerateContent" metadata.
        public enum StreamGenerateContent {
            /// Request type for "StreamGenerateContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_GenerateContentRequest
            /// Response type for "StreamGenerateContent".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_GenerateContentResponse
            /// Descriptor for "StreamGenerateContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService"),
                method: "StreamGenerateContent"
            )
        }
        /// Namespace for "EmbedContent" metadata.
        public enum EmbedContent {
            /// Request type for "EmbedContent".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_EmbedContentRequest
            /// Response type for "EmbedContent".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_EmbedContentResponse
            /// Descriptor for "EmbedContent".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService"),
                method: "EmbedContent"
            )
        }
        /// Namespace for "BatchEmbedContents" metadata.
        public enum BatchEmbedContents {
            /// Request type for "BatchEmbedContents".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest
            /// Response type for "BatchEmbedContents".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse
            /// Descriptor for "BatchEmbedContents".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService"),
                method: "BatchEmbedContents"
            )
        }
        /// Namespace for "CountTokens" metadata.
        public enum CountTokens {
            /// Request type for "CountTokens".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_CountTokensRequest
            /// Response type for "CountTokens".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_CountTokensResponse
            /// Descriptor for "CountTokens".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService"),
                method: "CountTokens"
            )
        }
        /// Descriptors for all methods in the "google.ai.generativelanguage.v1beta.GenerativeService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GenerateContent.descriptor,
            GenerateAnswer.descriptor,
            StreamGenerateContent.descriptor,
            EmbedContent.descriptor,
            BatchEmbedContents.descriptor,
            CountTokens.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.GenerativeService" service.
    public static let google_ai_generativelanguage_v1Beta_GenerativeService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.GenerativeService")
}

// MARK: google.ai.generativelanguage.v1beta.GenerativeService (client)

extension Google_Ai_Generativelanguage_V1beta_GenerativeService {
    /// Generated client protocol for the "google.ai.generativelanguage.v1beta.GenerativeService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > API for using Large Models that generate multimodal content and have
    /// > additional capabilities beyond text generation.
    public protocol ClientProtocol: Sendable {
        /// Call the "GenerateContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a model response given an input `GenerateContentRequest`.
        /// > Refer to the [text generation
        /// > guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed
        /// > usage information. Input capabilities differ between models, including
        /// > tuned models. Refer to the [model
        /// > guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning
        /// > guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func generateContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GenerateAnswer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a grounded answer from the model given an input
        /// > `GenerateAnswerRequest`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func generateAnswer<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "StreamGenerateContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a [streamed
        /// > response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
        /// > from the model given an input `GenerateContentRequest`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func streamGenerateContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "EmbedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a text embedding vector from the input `Content` using the
        /// > specified [Gemini Embedding
        /// > model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_EmbedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_EmbedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_EmbedContentResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func embedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "BatchEmbedContents" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates multiple embedding vectors from the input `Content` which
        /// > consists of a batch of strings represented as `EmbedContentRequest`
        /// > objects.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func batchEmbedContents<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CountTokens" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Runs a model's tokenizer on input `Content` and returns the token count.
        /// > Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens)
        /// > to learn more about tokens.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CountTokensRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CountTokensRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CountTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func countTokens<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "google.ai.generativelanguage.v1beta.GenerativeService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > API for using Large Models that generate multimodal content and have
    /// > additional capabilities beyond text generation.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GenerateContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a model response given an input `GenerateContentRequest`.
        /// > Refer to the [text generation
        /// > guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed
        /// > usage information. Input capabilities differ between models, including
        /// > tuned models. Refer to the [model
        /// > guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning
        /// > guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func generateContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_GenerativeService.Method.GenerateContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GenerateAnswer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a grounded answer from the model given an input
        /// > `GenerateAnswerRequest`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func generateAnswer<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_GenerativeService.Method.GenerateAnswer.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "StreamGenerateContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a [streamed
        /// > response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
        /// > from the model given an input `GenerateContentRequest`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateContentResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func streamGenerateContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_GenerativeService.Method.StreamGenerateContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "EmbedContent" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a text embedding vector from the input `Content` using the
        /// > specified [Gemini Embedding
        /// > model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_EmbedContentRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_EmbedContentRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_EmbedContentResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func embedContent<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_GenerativeService.Method.EmbedContent.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "BatchEmbedContents" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates multiple embedding vectors from the input `Content` which
        /// > consists of a batch of strings represented as `EmbedContentRequest`
        /// > objects.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func batchEmbedContents<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_GenerativeService.Method.BatchEmbedContents.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CountTokens" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Runs a model's tokenizer on input `Content` and returns the token count.
        /// > Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens)
        /// > to learn more about tokens.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CountTokensRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CountTokensRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CountTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func countTokens<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_GenerativeService.Method.CountTokens.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_GenerativeService.ClientProtocol {
    /// Call the "GenerateContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a model response given an input `GenerateContentRequest`.
    /// > Refer to the [text generation
    /// > guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed
    /// > usage information. Input capabilities differ between models, including
    /// > tuned models. Refer to the [model
    /// > guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning
    /// > guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.generateContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GenerateAnswer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a grounded answer from the model given an input
    /// > `GenerateAnswerRequest`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateAnswer<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.generateAnswer(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StreamGenerateContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a [streamed
    /// > response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
    /// > from the model given an input `GenerateContentRequest`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func streamGenerateContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.streamGenerateContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "EmbedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a text embedding vector from the input `Content` using the
    /// > specified [Gemini Embedding
    /// > model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_EmbedContentRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embedContent<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.embedContent(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "BatchEmbedContents" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates multiple embedding vectors from the input `Content` which
    /// > consists of a batch of strings represented as `EmbedContentRequest`
    /// > objects.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func batchEmbedContents<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.batchEmbedContents(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CountTokens" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Runs a model's tokenizer on input `Content` and returns the token count.
    /// > Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens)
    /// > to learn more about tokens.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CountTokensRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func countTokens<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.countTokens(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_GenerativeService.ClientProtocol {
    /// Call the "GenerateContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a model response given an input `GenerateContentRequest`.
    /// > Refer to the [text generation
    /// > guide](https://ai.google.dev/gemini-api/docs/text-generation) for detailed
    /// > usage information. Input capabilities differ between models, including
    /// > tuned models. Refer to the [model
    /// > guide](https://ai.google.dev/gemini-api/docs/models/gemini) and [tuning
    /// > guide](https://ai.google.dev/gemini-api/docs/model-tuning) for details.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_GenerateContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.generateContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GenerateAnswer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a grounded answer from the model given an input
    /// > `GenerateAnswerRequest`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateAnswer<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateAnswerResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateAnswerRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.generateAnswer(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StreamGenerateContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a [streamed
    /// > response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
    /// > from the model given an input `GenerateContentRequest`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func streamGenerateContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_GenerateContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateContentResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.streamGenerateContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "EmbedContent" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a text embedding vector from the input `Content` using the
    /// > specified [Gemini Embedding
    /// > model](https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embedContent<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_EmbedContentRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedContentResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedContentRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.embedContent(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "BatchEmbedContents" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates multiple embedding vectors from the input `Content` which
    /// > consists of a batch of strings represented as `EmbedContentRequest`
    /// > objects.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func batchEmbedContents<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedContentsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.batchEmbedContents(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CountTokens" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Runs a model's tokenizer on input `Content` and returns the token count.
    /// > Refer to the [tokens guide](https://ai.google.dev/gemini-api/docs/tokens)
    /// > to learn more about tokens.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func countTokens<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_CountTokensRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTokensRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.countTokens(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}