// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/text_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - google.ai.generativelanguage.v1beta.TextService

/// Namespace containing generated types for the "google.ai.generativelanguage.v1beta.TextService" service.
public enum Google_Ai_Generativelanguage_V1beta_TextService {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.TextService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.TextService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GenerateText" metadata.
        public enum GenerateText {
            /// Request type for "GenerateText".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_GenerateTextRequest
            /// Response type for "GenerateText".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_GenerateTextResponse
            /// Descriptor for "GenerateText".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.TextService"),
                method: "GenerateText"
            )
        }
        /// Namespace for "EmbedText" metadata.
        public enum EmbedText {
            /// Request type for "EmbedText".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_EmbedTextRequest
            /// Response type for "EmbedText".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_EmbedTextResponse
            /// Descriptor for "EmbedText".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.TextService"),
                method: "EmbedText"
            )
        }
        /// Namespace for "BatchEmbedText" metadata.
        public enum BatchEmbedText {
            /// Request type for "BatchEmbedText".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest
            /// Response type for "BatchEmbedText".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse
            /// Descriptor for "BatchEmbedText".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.TextService"),
                method: "BatchEmbedText"
            )
        }
        /// Namespace for "CountTextTokens" metadata.
        public enum CountTextTokens {
            /// Request type for "CountTextTokens".
            public typealias Input = Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest
            /// Response type for "CountTextTokens".
            public typealias Output = Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse
            /// Descriptor for "CountTextTokens".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.TextService"),
                method: "CountTextTokens"
            )
        }
        /// Descriptors for all methods in the "google.ai.generativelanguage.v1beta.TextService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GenerateText.descriptor,
            EmbedText.descriptor,
            BatchEmbedText.descriptor,
            CountTextTokens.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "google.ai.generativelanguage.v1beta.TextService" service.
    public static let google_ai_generativelanguage_v1Beta_TextService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "google.ai.generativelanguage.v1beta.TextService")
}

// MARK: google.ai.generativelanguage.v1beta.TextService (client)

extension Google_Ai_Generativelanguage_V1beta_TextService {
    /// Generated client protocol for the "google.ai.generativelanguage.v1beta.TextService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > API for using Generative Language Models (GLMs) trained to generate text.
    /// > 
    /// > Also known as Large Language Models (LLM)s, these generate text given an
    /// > input prompt from the user.
    public protocol ClientProtocol: Sendable {
        /// Call the "GenerateText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a response from the model given an input message.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateTextRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateTextRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func generateText<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "EmbedText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates an embedding from the model given an input message.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_EmbedTextRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_EmbedTextRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_EmbedTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func embedText<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "BatchEmbedText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates multiple embeddings from the model given input text in a
        /// > synchronous call.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func batchEmbedText<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CountTextTokens" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Runs a model's tokenizer on a text and returns the token count.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func countTextTokens<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "google.ai.generativelanguage.v1beta.TextService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > API for using Generative Language Models (GLMs) trained to generate text.
    /// > 
    /// > Also known as Large Language Models (LLM)s, these generate text given an
    /// > input prompt from the user.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GenerateText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates a response from the model given an input message.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateTextRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_GenerateTextRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_GenerateTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func generateText<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_TextService.Method.GenerateText.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "EmbedText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates an embedding from the model given an input message.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_EmbedTextRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_EmbedTextRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_EmbedTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func embedText<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_TextService.Method.EmbedText.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "BatchEmbedText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Generates multiple embeddings from the model given input text in a
        /// > synchronous call.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func batchEmbedText<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_TextService.Method.BatchEmbedText.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CountTextTokens" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Runs a model's tokenizer on a text and returns the token count.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest` message.
        ///   - serializer: A serializer for `Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest` messages.
        ///   - deserializer: A deserializer for `Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func countTextTokens<Result>(
            request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Google_Ai_Generativelanguage_V1beta_TextService.Method.CountTextTokens.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_TextService.ClientProtocol {
    /// Call the "GenerateText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a response from the model given an input message.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_GenerateTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateText<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.generateText(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "EmbedText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates an embedding from the model given an input message.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_EmbedTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embedText<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.embedText(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "BatchEmbedText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates multiple embeddings from the model given input text in a
    /// > synchronous call.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func batchEmbedText<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.batchEmbedText(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CountTextTokens" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Runs a model's tokenizer on a text and returns the token count.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func countTextTokens<Result>(
        request: GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.countTextTokens(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Google_Ai_Generativelanguage_V1beta_TextService.ClientProtocol {
    /// Call the "GenerateText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates a response from the model given an input message.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateText<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_GenerateTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_GenerateTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_GenerateTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.generateText(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "EmbedText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates an embedding from the model given an input message.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embedText<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_EmbedTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_EmbedTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_EmbedTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.embedText(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "BatchEmbedText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Generates multiple embeddings from the model given input text in a
    /// > synchronous call.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func batchEmbedText<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.batchEmbedText(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CountTextTokens" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Runs a model's tokenizer on a text and returns the token count.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func countTextTokens<Result>(
        _ message: Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.countTextTokens(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}